### ISSUE TITLE
spawn npm ENOENT

### ISSUE THREAD

**Issue by samikhaled** [jkuri/angular-rollup-starter#1]
d:\AngularJS\Tutorials\New\Apps\angular2-rollup-starter>npm run serve

> angular2-rollup-starter@1.0.0 serve d:\AngularJS\Tutorials\New\Apps\angular2-rollup-starter
> node ./scripts/server.js

Starting initial build...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "D:\Apps\NodeData\npm\node_modules\npm\bin\npm-cli.js" "run" "serve"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-rollup-starter@1.0.0 serve: `node ./scripts/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-rollup-starter@1.0.0 serve script 'node ./scripts/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-rollup-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-rollup-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-rollup-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\AngularJS\Tutorials\New\Apps\angular2-rollup-starter\npm-debug.log

**Comment by jkuri** [comment]
Thanks for notice. Can you please check again?

**Comment by samikhaled** [comment]
I installed the latest project update
and I have the same error.

**Comment by jkuri** [comment]
@samikhaled on Windows maybe?

**Comment by RedForza** [comment]
Got the same issue. On Windows 10.

**Comment by jkuri** [comment]
Thanks for reporting, let me check that on Windows and I'll make a fix asap.

**Comment by jkuri** [comment]
https://github.com/jkuri/angular2-rollup-starter/commit/311bf282826c0256b3361829e3e07daaeb9df590

**Comment by VIPINSAINI17** [comment]
Hi , I am facing below issue while running on windows 10.
I like your article .. it fit with my requirements , however unfortunately I am not able to run locally

Error: spawn npm ENOENT
at exports._errnoException (util.js:1008:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
at onErrorNT (internal/child_process.js:348:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by VIPINSAINI17** [comment]
I appreciate if you help me to get it fixed

**Comment by jkuri** [comment]
can you please provide full error?

**Comment by VIPINSAINI17** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'roll' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'preroll', 'roll', 'postroll' ]
5 info lifecycle angular2-rollup-starter@1.0.0~preroll: angular2-rollup-starter@1.0.0
6 silly lifecycle angular2-rollup-starter@1.0.0~preroll: no script for preroll, continuing
7 info lifecycle angular2-rollup-starter@1.0.0~roll: angular2-rollup-starter@1.0.0
8 verbose lifecycle angular2-rollup-starter@1.0.0~roll: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-rollup-starter@1.0.0~roll: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Pluralsight Trainings\AngularJS2.0\ng2-file-manager-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\VIPINK\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\VIPINK\AppData\Roaming\npm
10 verbose lifecycle angular2-rollup-starter@1.0.0~roll: CWD: C:\Pluralsight Trainings\AngularJS2.0\ng2-file-manager-master
11 silly lifecycle angular2-rollup-starter@1.0.0~roll: Args: [ '/d /s /c', 'node ./scripts/cmd.js dist' ]
12 silly lifecycle angular2-rollup-starter@1.0.0~roll: Returned: code: 1  signal: null
13 info lifecycle angular2-rollup-starter@1.0.0~roll: Failed to exec roll script
14 verbose stack Error: angular2-rollup-starter@1.0.0 roll: `node ./scripts/cmd.js dist`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-rollup-starter@1.0.0
16 verbose cwd C:\Pluralsight Trainings\AngularJS2.0\ng2-file-manager-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "roll"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-rollup-starter@1.0.0 roll: `node ./scripts/cmd.js dist`
22 error Exit status 1
23 error Failed at the angular2-rollup-starter@1.0.0 roll script 'node ./scripts/cmd.js dist'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-rollup-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./scripts/cmd.js dist
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-rollup-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-rollup-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by VIPINSAINI17** [comment]
when I have performed - npm run roll

**Comment by jkuri** [comment]
can you try to change typescript version to match exact 2.0.10 in package.json, then remove node_modules and install it again.

**Comment by VIPINSAINI17** [comment]
> angular2-rollup-starter@1.0.0 roll C:\Pluralsight Trainings\AngularJS2.0\ng2-file-manager-master
> node ./scripts/cmd.js dist

Prepairing project for production, please wait...
-------------------------------------------------------
C:\Pluralsight Trainings\AngularJS2.0\ng2-file-manager-master\dist deleted.
/public dir successfully copied to dist.
index.html generated at C:\Pluralsight Trainings\AngularJS2.0\ng2-file-manager-master\dist\index.html
SASS compiled in 71ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rollup ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "roll"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-rollup-starter@1.0.0 roll: `node ./scripts/cmd.js dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-rollup-starter@1.0.0 roll script 'node ./scripts/cmd.js dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-rollup-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:

**Comment by VIPINSAINI17** [comment]
I have installed typescript@2.0.10 & deleted node_modules , however I still get same error.

**Comment by jkuri** [comment]
Looks like you are running some really old version of this starter. Can you
clone the latest?

**Comment by VIPINSAINI17** [comment]
I have tried all the options ..no luck yet.... Can you please help..? I appreciate your help

**Comment by jkuri** [comment]
Please check last message.

**Comment by VIPINSAINI17** [comment]
I have taken latest code from repo ...very latest .. I am using given version - " Latest commit 246aaf6  on Sep 4"

**Comment by jkuri** [comment]
Looks like we are not talking about same projects, last commit from this project is Dec 5.
