### ISSUE TITLE
Karma tests not working

### ISSUE THREAD

**Issue by marcoturi** [jkuri/angular-rollup-starter#3]
Commands:

```
npm i
npm run test
```

Results in:

> 03 10 2016 10:16:38.508:ERROR [preprocessor.rollup]: Could not load C:\Users\Mar                                                                                co\Sources\Github\angular2-rollup-starter\node_modules\rxjs-es/Rx (imported by C                                                                                :\Users\Marco\Sources\Github\angular2-rollup-starter\src\test.ts): ENOENT: no su                                                                                ch file or directory, open 'C:\Users\Marco\Sources\Github\angular2-rollup-starte                                                                                r\node_modules\rxjs-es\Rx'
>  at C:/Users/Marco/Sources/Github/angular2-rollup-starter/src/test.ts
> Error: Could not load C:\Users\Marco\Sources\Github\angular2-rollup-starter\node                                                                                _modules\rxjs-es/Rx (imported by C:\Users\Marco\Sources\Github\angular2-rollup-s                                                                                tarter\src\test.ts): ENOENT: no such file or directory, open 'C:\Users\Marco\Sou                                                                                rces\Github\angular2-rollup-starter\node_modules\rxjs-es\Rx'
>     at C:\Users\Marco\Sources\Github\angular2-rollup-starter\node_modules\rollup                                                                                \dist\rollup.js:8775:10
> 03 10 2016 10:16:38.516:INFO [karma]: Karma v1.3.0 server started at http://loca                                                                                lhost:9876/
> 03 10 2016 10:16:38.517:INFO [launcher]: Launching browser Chrome with unlimited                                                                                 concurrency
> 03 10 2016 10:16:38.524:INFO [launcher]: Starting browser Chrome
> 03 10 2016 10:16:41.836:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on                                                                                 socket /#Md2yDVtUkbO4HHUYAAAA with id 90653529
> Chrome 53.0.2785 (Windows 10 0.0.0) ERROR
>   You need to include some adapter that implements __karma__.start method!

**Comment by jkuri** [comment]
@marcoturi thanks for report, will check into this.

**Comment by marcoturi** [comment]
this could help -> https://github.com/ngrx/db/blob/master/tests.bundle.ts

**Comment by jkuri** [comment]
Hi, can you try the new update, I got:

``` bash
Chrome 53.0.2785 (Mac OS X 10.12.0): Executed 2 of 2 SUCCESS (0.254 secs / 0.246 secs)
```

**Comment by jkuri** [comment]
https://github.com/jkuri/angular2-rollup-starter/commit/4960201a82554ab5483720722f4db70ea019bb55 should solve this. Checked on Windows.
