### ISSUE TITLE
Error headling

### ISSUE THREAD

**Issue by tamascsaba** [jkuri/angular-rollup-starter#5]
Rollup build does not handle error, if i misspell something, build also successful a good example:
`app.component.ts`

``` typescript
import { wrongComponent } from '@angular/core';
import * as rx from 'rxjs';
import * as moment from 'moment';

missingglobal.init('');

console.loggggg(rx, moment);

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {
  title = 'app works!';
}
```

```
[BS] File changed: dist/main.js.map
[BS] File changed: dist/main.js
Build time (main): 2799ms

```

**Comment by tamascsaba** [comment]
@jkuri ??

**Comment by jkuri** [comment]
hey @tamascsaba thanks for notice, I think that worked for me but really I need to check and make a fix asap. I hope that'll happen today.

**Comment by tamascsaba** [comment]
awesome :+1:

**Comment by jkuri** [comment]
Hi @tamascsaba, sorry for late response. This should be resolved with https://github.com/jkuri/angular2-rollup-starter/commit/9afbd6cf09bbb3b3d9d7c94264fbd146144d690b.
